name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: yarn install

    - name: Install CocoaPods dependencies
      run: cd ios && pod install

    - name: Build iOS project for simulator
      run: xcodebuild -workspace ios/CITestingApp.xcworkspace -scheme CITestingApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5' build

    - name: Run Tests on iOS simulator
      run: |
        xcodebuild \
          -workspace ios/CITestingApp.xcworkspace \
          -scheme CITestingApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5' \
          test
