name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Lint Code
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Build Android
        run: cd android && ./gradlew assembleRelease

      - name: Build iOS
        run: cd ios && xcodebuild -workspace CITestingApp.xcworkspace -scheme CITestingApp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/CITestingApp.xcarchive
      
      - name: Upload APK to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws s3 cp android/app/build/outputs/apk/release/app-release.apk s3://dreamapplication/apks/ --region $AWS_REGION

    